name: Deploy Collector

on:
  workflow_dispatch:
    inputs:
      aws_access_key_id:
        description: 'AWS Access Key ID'
        required: true
      aws_secret_access_key:
        description: 'AWS Secret Access Key'
        required: true
      aws_session_token:
        description: 'AWS Session Token'
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    outputs: # Definir outputs del job
      sqs_queue_url: ${{ steps.export_outputs.outputs.sqs_queue_url }}
      scraper_ip: ${{ steps.export_outputs.outputs.scraper_ip }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ github.event.inputs.aws_access_key_id }}
          aws-secret-access-key: ${{ github.event.inputs.aws_secret_access_key }}
          aws-session-token: ${{ github.event.inputs.aws_session_token }}
          aws-region: us-east-1
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init

      - name: Deploy Collector with Terraform
        run: terraform apply -auto-approve

      - name: Debug Terraform
        run: |
          terraform output

      - name: Export Outputs
        id: export_outputs # ID para referenciar los outputs
        run: |
          echo "::set-output name=sqs_queue_url::$(terraform output -raw sqs_queue_url)"
          echo "::set-output name=scraper_ip::$(terraform output -raw collector_public_ip)"

      - name: Destroy Collector
        run: terraform destroy -auto-approve
