name: Deploy Collector

on:
  workflow_dispatch:
    inputs:
      aws_access_key_id:
        description: 'AWS Access Key ID'
        required: true
      aws_secret_access_key:
        description: 'AWS Secret Access Key'
        required: true
      aws_session_token:
        description: 'AWS Session Token'
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ github.event.inputs.aws_access_key_id }}
          aws-secret-access-key: ${{ github.event.inputs.aws_secret_access_key }}
          aws-session-token: ${{ github.event.inputs.aws_session_token }}
          aws-region: us-east-1
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init

      - name: Deploy Collector with Terraform
        run: terraform apply -auto-approve

      - name: Debug Terraform
        run: |
          terraform output

      - name: Export Outputs
        run: |
          SQS_QUEUE_URL=$(terraform output -raw sqs_queue_url)
          SCRAPER_IP=$(terraform output -raw ec2_public_ip)
          echo "SQS_QUEUE_URL=$SQS_QUEUE_URL"
          echo "SCRAPER_IP=$SCRAPER_IP"

      - name: Destroy Collector
        run: terraform destroy -auto-approve
